//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMV.PEP.ViewModel.ServicePassagemPlantao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePassagemPlantao.IPassagemPlantaoEmergencia")]
    public interface IPassagemPlantaoEmergencia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassagemPlantaoEmergencia/AdicionarMensagem", ReplyAction="http://tempuri.org/IPassagemPlantaoEmergencia/AdicionarMensagemResponse")]
        void AdicionarMensagem(string mensagem, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassagemPlantaoEmergencia/AtualizaPassagem", ReplyAction="http://tempuri.org/IPassagemPlantaoEmergencia/AtualizaPassagemResponse")]
        void AtualizaPassagem(int pAtendimento, string pPlano, string pListaProblemas, string pEnfermagem, int pIdLocalPaciente, string pUsuario, bool pAtualizaLista);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPassagemPlantaoEmergenciaChannel : HMV.PEP.ViewModel.ServicePassagemPlantao.IPassagemPlantaoEmergencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassagemPlantaoEmergenciaClient : System.ServiceModel.ClientBase<HMV.PEP.ViewModel.ServicePassagemPlantao.IPassagemPlantaoEmergencia>, HMV.PEP.ViewModel.ServicePassagemPlantao.IPassagemPlantaoEmergencia {
        
        public PassagemPlantaoEmergenciaClient() {
        }
        
        public PassagemPlantaoEmergenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassagemPlantaoEmergenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassagemPlantaoEmergenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassagemPlantaoEmergenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AdicionarMensagem(string mensagem, string nome) {
            base.Channel.AdicionarMensagem(mensagem, nome);
        }
        
        public void AtualizaPassagem(int pAtendimento, string pPlano, string pListaProblemas, string pEnfermagem, int pIdLocalPaciente, string pUsuario, bool pAtualizaLista) {
            base.Channel.AtualizaPassagem(pAtendimento, pPlano, pListaProblemas, pEnfermagem, pIdLocalPaciente, pUsuario, pAtualizaLista);
        }
    }
}
