//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMV.PEP.Test.SendEmail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendEmail.ISendEmailService")]
    public interface ISendEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendEmailService/Send", ReplyAction="http://tempuri.org/ISendEmailService/SendResponse")]
        void Send(string emailto, string subjecttext, string bodyText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendEmailServiceChannel : HMV.PEP.Test.SendEmail.ISendEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailServiceClient : System.ServiceModel.ClientBase<HMV.PEP.Test.SendEmail.ISendEmailService>, HMV.PEP.Test.SendEmail.ISendEmailService {
        
        public SendEmailServiceClient() {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(string emailto, string subjecttext, string bodyText) {
            base.Channel.Send(emailto, subjecttext, bodyText);
        }
    }
}
